spring:
  application:
    name: repotrack
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
repo:
  fetch:
    cron: ${REPO_FETCH_CRON:0 59 23 * * *}
repositories: ${REPOSITORY_LIST:}


